/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2022.Jlogo;

import it.unicam.cs.pa2022.Jlogo.view.TerminalView;

import java.io.IOException;


public class App {

    public static void main(String[] args) throws IOException {
        TerminalView.init();

    }
}
